package com.kamath.propalert.infrastructure.mapping;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.kamath.propalert.domain.model.Lead;
import com.propalert.infrastructure.web.dto.LeadRequest;

@Mapper(componentModel = "spring")
public interface LeadMapper {
    @Mapping(target = "id", ignore = true) // ID will be generated by the DB
    Lead toDomain(LeadRequest dto);

    LeadRequest toDto(Lead domain);
}
