package com.kamath.propalert.infrastructure.mapping;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.kamath.propalert.domain.model.Lead;
import com.kamath.propalert.infrastructure.persistence.entity.LeadEntity;
import com.propalert.infrastructure.web.dto.LeadRequest;

@Mapper(componentModel = "spring")
public interface LeadMapper {

    // STEP 1: External World -> Domain Core
    // This is what the Service receives from the Controller
    // ID will be generated by the DB
    @Mapping(target = "id", ignore = true)
    Lead toDomainFromRequest(LeadRequest request);

    // STEP 2: Domain Core -> Database Entity
    // This is what the Service sends to the Repository
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "brokerId", ignore = true)
    LeadEntity toEntityFromDomain(Lead domain);

    /**
     * STEP 3: ENTITY -> DOMAIN
     * Used when fetching data from the Database back into the Application.
     */
    Lead toDomainFromEntity(LeadEntity entity);

    // Domain -> Web DTO
    LeadRequest toDtoFromDomain(Lead domain);
}
