openapi: 3.0.3
info:
  title: Prop-Alert India API
  version: 1.0.0
paths:
  /health:
    get:
      summary: System health check
      responses:
        "200":
          description: OK
  /brokers:
    $ref: './paths/Broker-paths.yaml'
  /leads:
    $ref: './paths/lead-paths.yaml'